name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # fetch tags - tags are needed for versionPolicyCheck binary and source compat checks
          fetch-tags: true
      - uses: coursier/cache-action@v6
      # SBT 1 base JDK version is 1.8
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: sbt build
        run: sbt clean buildFull
